add task 02_functions solution
dmitry-sidorov/wgforge_platform_frontend_course pull request #7
Opened 2019-04-15 09:39 UTC by dmitry-sidorov

1) main task done
2) options in arguments task done
3) escaping quotes task done

re-opened PR (from 09.04.19)

2019-04-16 08:43 UTC, PavloKovalov approved these changes
🆗

2019-04-16 08:43 UTC, PavloKovalov commented on 02_functions/practice/exercises/query.js
> +    const isQuery = query => query.__proto__.constructor.name === 'Query';
```javascript
const isQuery = q=> q instanceof Query
```
может так?

2019-04-16 08:43 UTC, PavloKovalov commented on 02_functions/practice/exercises/query.js
> +    const isQuery = query => query.__proto__.constructor.name === 'Query';
и обрати внимание, что сейчас именование query совпадает с именем родительской функции

2019-04-16 08:43 UTC, PavloKovalov commented on 02_functions/practice/exercises/query.js
> +    function WhereObject(that) {
лучше давать более осмысленные имена переменным и аргументам

2019-04-16 13:06 UTC, dmitry-sidorov commented on 02_functions/practice/exercises/query.js
> +    function WhereObject(that) {
ты про WhereObject?

2019-04-16 13:18 UTC, dmitry-sidorov commented on 02_functions/practice/exercises/query.js
> +    const isQuery = query => query.__proto__.constructor.name === 'Query';
`const isQuery = obj => obj instanceof Query;`

[поправил](https://github.com/dmitry-sidorov/wgforge_platform_frontend_course/pull/7/commits/6b12b72cd13ae7a8b3bbca8033f57dc9959a47e9)

2019-04-16 15:46 UTC, artur-code requested changes
Нужны правки по комментариям

2019-04-16 15:46 UTC, artur-code commented on 02_functions/practice/exercises/query.js
> +  switch (params.length) {
˜19 лишних строчек кода которые можно заменить параметра со значением по умолчанию query(tableName, options = {}) и парой строк кода на обработку исключений при некоректных типах переданных параметров

2019-04-16 15:46 UTC, artur-code commented on 02_functions/practice/exercises/query.js
> +    let whereUsed = false;
whereUsed -  "где используется", по смыслу переменная вводит в заблуждение как будто в ней текстовое значение а не логический признак. Boolean переменные хорошо именовать с префиксами is или has, например hasWhereOperator, isOperatorWhere и подобные. С переменными ниже аналогично

2019-04-24 03:55 UTC, dmitry-sidorov commented on 02_functions/practice/exercises/query.js
> +  switch (params.length) {
[исправил](https://github.com/dmitry-sidorov/wgforge_platform_frontend_course/pull/7/commits/0949e9a61a9bd87123141163d079f5688757907f)

2019-04-24 03:58 UTC, dmitry-sidorov commented on 02_functions/practice/exercises/query.js
> +    let whereUsed = false;
[cheers](https://github.com/dmitry-sidorov/wgforge_platform_frontend_course/pull/7/commits/a50c5f53a640ef8437ebf38ac12e0431b678efb4)

2024-11-13 21:44 UTC, closed without merging