Task 03 iterators
dmitry-sidorov/wgforge_platform_frontend_course pull request #8
Opened 2019-04-16 14:11 UTC by dmitry-sidorov

:rocket:

2019-04-16 15:30 UTC, artur-code requested changes

2019-04-16 15:30 UTC, artur-code commented on 03_iterators/practice/exercises/cloneDeep.js
> +export default function cloneDeep(sourceObject) {
Немного переусложнил, на самом деле все равно у тебя object или array ты должен делать рекурсивные вызовы для всех значений у которых typeof "object"  (typeof [] === "object")и они не null, тогда ты всегда к простым типам будешь приходить

2019-04-16 15:30 UTC, artur-code commented on 03_iterators/practice/exercises/deepMerge.js
> +  const isArray = obj => obj.__proto__.constructor.name.toLowerCase() === 'array';
есть же Array.isArray

2019-04-16 15:30 UTC, artur-code commented on 03_iterators/practice/exercises/deepMerge.js
>  export default function deepMerge(destinationObject, sourceObject) {
Код в функции отформатирован без отступов, тяжело читать.  Нужны отступы хотя бы между внутренними объявлениями функций

2019-04-16 20:14 UTC, dmitry-sidorov commented on 03_iterators/practice/exercises/cloneDeep.js
> +export default function cloneDeep(sourceObject) {
я тоже так думал, пока не получил вместо массива объект вида {0: {name: 'vasya'}, 1: {surname: 'ivanov'}} 😂 надо условия в if-ах перепроверить, спасибо за обратную связь👌

2019-04-17 13:39 UTC, dmitry-sidorov commented on 03_iterators/practice/exercises/deepMerge.js
> +  const isArray = obj => obj.__proto__.constructor.name.toLowerCase() === 'array';
исправил

2019-04-17 14:01 UTC, dmitry-sidorov commented on 03_iterators/practice/exercises/deepMerge.js
>  export default function deepMerge(destinationObject, sourceObject) {
ты имеешь в виду так: 
```javascript
const isObject = obj => typeof obj === 'object';

const isUndefined = obj => typeof obj === 'undefined';
```
или так:
```javascript
const isObject = obj => {
  return typeof obj === 'object';
}

const isUndefined = obj => {
  return typeof obj === 'undefined';
}
```
?

2024-11-13 21:45 UTC, closed without merging